# This is an updated .gitlab-ci.yml file
# Define the stages of your pipeline
stages:
  - build
  - test
  - deploy

# Define the jobs to be executed within each stage
# Jobs are executed in parallel unless explicitly dependent on each other

# Build stage
build_server:
  stage: build
  script:
    - docker build -t fightthelandlord-server ./server
    - docker image ls

build_ui:
  stage: build
  script:
    - docker build -t fightthelandlord-ui ./ui
    - docker image ls


deploy:
  stage: deploy
  script:
    - ls
    - kubectl config get-contexts
    - kubectl create -f k8s/