# This is an updated .gitlab-ci.yml file
image: node:latest
# Define the stages of your pipeline
stages:
  - build
  - test
  - deploy

# Define the jobs to be executed within each stage
# Jobs are executed in parallel unless explicitly dependent on each other

# Build stage
build_ui:
  stage: build
  script:
    - cd ui
    - npm install
    - vite build
build_server:
  stage: build
  script:
    - cd ../server
    - npm install
    - vite build
# # Test stage
# test:
#   stage: test
#   script:
#     - cd ui
#     - npm install
#     - npm test
#     - cd ../server
#     - npm install
#     - npm test

# # Deploy stage
deploy:
  stage: deploy
  script:
    - echo "Deploying the project..."