# This is an updated .gitlab-ci.yml file
# Define the stages of your pipeline
stages:
  - build
  - deploy
  - e2e_test

# Define the jobs to be executed within each stage
# Jobs are executed in parallel unless explicitly dependent on each other

# Build stage
build_server:
  stage: build
  script:
    - docker build -t fightthelandlord-server ./server
    - docker image ls

build_ui:
  stage: build
  script:
    - docker build -t fightthelandlord-ui ./ui
    - docker image ls


deploy:
  stage: deploy
  script:
    - ls
    - echo "$KUBECONFIG_CONTENT" > ./kubeconfig  
    - export KUBECONFIG=./kubeconfig  
    - kubectl config get-contexts  
    - kubectl create -f k8s/
    - kubectl delete -f k8s/

before_script:
  - curl -sL https://deb.nodesource.com/setup_14.x | bash -
  - apt-get install -y nodejs
  - node -v
  - npm -v

e2e_tests:
  stage: e2e_test
  script:
    - npm version
  #   - npx playwright install
  #   - npx playwright test --project=webkit
  # artifacts:
  #   when: always
  #   reports:
  #     junit: tests/results/*.xml